export const LANGS = ["en", "ta", "te", "kn", "hi", "sa"];

export const LANGUAGE_NAMES = {
  en: "English",
  ta: "தமிழ்",
  te: "తెలుగు",
  kn: "ಕನ್ನಡ",
  hi: "हिन्दी",
  sa: "संस्कृतम्",
};

export const UI_TEXT = {
  title: {
    en: "Acharya parampara",
    ta: "ஆச்சார்ய பரம்பரை",
    te: "ఆచార్య పరంపర",
    kn: "ಆಚಾರ್ಯ ಪರಂಪರೆ",
    hi: "आचार्य परम्परा",
    sa: "आचार्यपरम्परा",
  },
  language: {
    en: "Language",
    ta: "மொழி",
    te: "భాష",
    kn: "ಭಾಷೆ",
    hi: "भाषा",
    sa: "भाषा",
  },
  homeHeading: {
    en: "Acharyas and Birth Days",
    ta: "ஆச்சார்யர்களும் அவர்களின் பிறந்த தினங்களும்",
    te: "ఆచార్యులు మరియు వారి జన్మ దినాలు",
    kn: "ಆಚಾರ್ಯರು ಮತ್ತು ಅವರ ಜನ್ಮ ದಿನಗಳು",
    hi: "आचार्य और उनके जन्म दिवस",
    sa: "आचार्याः तथा तेषां जन्मदिनानि",
  },
  birthDay: {
    en: "Birth Day",
    ta: "பிறந்த நாள்",
    te: "జన్మ దినం",
    kn: "ಜನ್ಮ ದಿನ",
    hi: "जन्म दिवस",
    sa: "जन्मदिनम्",
  },
  notFound: {
    en: "Acharya data not found.",
    ta: "ஆச்சார்யர் தகவல் கிடைக்கவில்லை.",
    te: "ఆచార్య సమాచారం దొరకలేదు.",
    kn: "ಆಚಾರ್ಯ ಮಾಹಿತಿ ದೊರಕಲಿಲ್ಲ.",
    hi: "आचार्य का विवरण नहीं मिला।",
    sa: "आचार्यस्य विवरणं न लब्धम्।",
  },
  description: {
    en: "Description",
    ta: "விளக்கம்",
    te: "వివరణ",
    kn: "ವಿವರಣೆ",
    hi: "विवरण",
    sa: "वर्णनम्",
  },
};

export const META_LABELS = {
  name: {
    en: "Name",
    ta: "பெயர்",
    te: "పేరు",
    kn: "ಹೆಸರು",
    hi: "नाम",
    sa: "नाम",
  },
  birthYear: {
    en: "Birth Year",
    ta: "பிறந்த ஆண்டு",
    te: "జన్మ సంవత్సరం",
    kn: "ಜನ್ಮ ವರ್ಷ",
    hi: "जन्म वर्ष",
    sa: "जन्मवर्षम्",
  },
  birthNakshatra: {
    en: "Birth Nakshatra",
    ta: "பிறந்த நக்ஷத்திரம்",
    te: "జన్మ నక్షత్రం",
    kn: "ಜನ್ಮ ನಕ್ಷತ್ರ",
    hi: "जन्म नक्षत्र",
    sa: "जन्मनक्षत्रम्",
  },
  otherNames: {
    en: "Other Names",
    ta: "மற்ற பெயர்கள்",
    te: "ఇతర పేర్లు",
    kn: "ಇತರೆ ಹೆಸರುಗಳು",
    hi: "अन्य नाम",
    sa: "अन्यनामानि",
  },
  sishyas: {
    en: "Sishyas",
    ta: "சிஷ்யர்கள்",
    te: "శిష్యులు",
    kn: "ಶಿಷ್ಯರು",
    hi: "शिष्य",
    sa: "शिष्याः",
  },
  thaniyan: {
    en: "Thaniyan",
    ta: "தனியன்",
    te: "తనియన్",
    kn: "ತನಿಯನ್",
    hi: "तानियन्",
    sa: "तनियन्",
  },
  birthPlace: {
    en: "Birth Place",
    ta: "பிறந்த இடம்",
    te: "జన్మ స్థలం",
    kn: "ಜನ್ಮ ಸ್ಥಳ",
    hi: "जन्म स्थान",
    sa: "जन्मस्थानम्",
  },
};
